import { Inter } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Trip Planner',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <h1>Trip Planner</h1>
        </header>
        <main className={styles.mainContent}>{children}</main>
        <footer className={styles.footer}>
          <p>&copy; 2024 Trip Planner. All rights reserved to Tomer Menashe.</p>
        </footer>
      </body>
    </html>
  );
}
